Added 3D Gaussian Splatting Renderer and sorted showcases alphabetically
gfx-rs/wgpu-rs.github.io pull request #36
Opened 2024-03-15 15:14 UTC by KeKsBoTer

I added [my project](https://github.com/KeKsBoTer/web-splat) to the showcases.

Also, I sorted the showcases alphabetically.

2026-02-24 19:20 UTC, inner-daemons requested changes
This was put up a while ago but it looks like you have been working on the project as recently as 5 months ago so its still worth considering for merging.

I think the idea to alphabetize is probably not what we're going for, but I'll let someone else weigh in on that later. In any case that should be in another PR.

I'm also not sure why you uploaded 2 screenshots but only used one.

If you are willing, I'd still like to have this merged if you get to these points. I'll also bring it up with actual maintainers soon so we can get a verdict.

2026-02-26 10:32 UTC, KeKsBoTer commented
Thanks for the feedback! 
I am still working on the project / maintaining it. 

I dont remember why I uploaded two images... I deleted the unused one.

2026-02-27 22:36 UTC, inner-daemons approved these changes
I definitely don't think we should alphebetize the examples list. But I'm gonna approve this for now on the condition that the next reviewer opines on that point.

2026-03-10 01:21 UTC, cwfitzgerald commented
Yeah please remove the alphabetization from this PR - we can discuss it separately.

2026-03-10 10:07 UTC, KeKsBoTer commented
I removed the alphabetization and appended my project.

2026-03-10 13:20 UTC, cwfitzgerald approved these changes
Thanks!

2026-03-10 16:02 UTC, merged